title: Fábio C. C. Meneghetti
url: "https://fabiom.net"
  #baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: "Based on Jekyll theme: <a style='color:black' href='https://github.com/ankitsultana/researcher'>Researcher</a>"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"

twitter_username: fabiomeneg
